version: "3.7"
volumes:
  db:
    driver:
      local
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: elearning
    container_name: elearning-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www:cached
    networks:
      - elearning-network

  db:
    image: mysql:5.7
    container_name: elearning-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: elearning
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - elearning-network

  nginx:
    image: nginx:alpine
    container_name: elearning-nginx
    restart: unless-stopped
    ports:
      - 443:80
    volumes:
      - ./:/var/www
      - ./touch.conf:/etc/nginx/conf.d/default.conf
    networks:
      - elearning-network

networks:
  elearning-network:
    driver: bridge
    external: true
